spring.application.name=cuentas
spring.data.mongodb.uri=mongodb://localhost:27017/bank_db

microservicios.clientes.url=http://localhost:8081

logging.level.com.banco.cuentas=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG